name: PHP Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Static analysis for PHP ${{ matrix.php }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        php: ['7.2', '7.3', '7.4', '8.0', '8.1', '8.2']
        os: ['ubuntu-latest']

    steps:
      - name: Checkout code base
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpcs

      - name: Setup dependencies
        run: |
          composer require -n --no-progress overtrue/phplint ipl/i18n:@dev
          git clone --depth 1 https://github.com/Icinga/icingaweb2.git vendor/icingaweb2
          git clone --depth 1 https://github.com/Icinga/icingadb-web.git vendor/icingadb-web
          git clone --depth 1 -b snapshot/nightly https://github.com/Icinga/icinga-php-thirdparty.git vendor/icinga-php-thirdparty

      - name: PHP Lint
        if: success() || matrix.allow_failure
        run: ./vendor/bin/phplint -n --exclude={^vendor/.*} -- .

      - name: PHP CodeSniffer
        if: success() || matrix.allow_failure
        run: phpcs

      - name: PHPStan
        uses: php-actions/phpstan@v3
        if: success() || matrix.allow_failure
